name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --frozen

    - name: Run tests
      run: uv run pytest -q

    - name: Run code quality checks
      run: |
        uv run black --check src/ tests/
        uv run mypy src/

    - name: Test CLI functionality
      run: |
        uv run sleepstack --help
        uv run sleepstack --version
        uv run sleepstack --list-vibes

    - name: Test package installation
      run: |
        uv tool install .
        sleepstack --version

    - name: Test audio generation (smoke test)
      run: |
        uv run sleepstack --vibe calm -a campfire -s 1
        ls -la build/binaural/
        ls -la build/mix/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --frozen

    - name: Build package
      run: uv build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
